version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: local-ai-chat-frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:9090
    stdin_open: true
    tty: true
